#!/usr/bin/env python3
import os
import argparse
import pandas as pd

def load_dat(filename: str):
    with open(filename, 'rb') as f:
        data = f.read()
    lines = [l[4:-3] for l in data.split(b"\n") if l.startswith(b"C '")]
    lines = [{e[0]: e[1] for e in (e.split(b"\x02") for e in l.split(b"\x01"))} for l in lines]
    return pd.DataFrame(lines)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', help="path to the coverage.dat file generated by verilator", required=True)
    parser.add_argument('CMD', help="command to execute on the coverage data")
    args =  parser.parse_args()
    if not os.path.isfile(args.input):
        raise RuntimeError(f"Wasn't able to find {args.input}")
    if args.CMD not in commands:
        raise RuntimeError(f"Unknown command `{args.CMD}`!\nTry instead: " + " ".join(commands.keys()))
    return args.input, args.CMD

def show(data):
    print(data)

commands = {
    'show': show
}

def main():
    filename, cmd = parse_args()
    data = load_dat(filename)
    commands[cmd](data)

if __name__ == '__main__':
    main()